version: '3'

services:
  mysql_db:
    image: mysql_db
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'zssn_db'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    networks:
      - app-tier

  python_app:
    container_name: zssn_app

    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    links:
      - mysql_db
    ports:
      - "5000:5000"
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge