version: '3'

services:
  mysql_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'zssn_db'
      MYSQL_PASSWORD: 'password'
    ports:
      - '3306:3306'
    networks:
      - app-tier
    volumes: 
    - ./docker/mysql/data:/var/lib/mysql:rw
    - ./database/zssn_db.sql:/docker-entrypoint-initdb.d/zssn_db.sql:ro

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    ports:
      - "5000:5000"
    networks:
      - app-tier
    command:
      tail -f /dev/null

networks:
  app-tier:
    driver: bridge